name: granddebat
dependencies:
  - python=3.6
  - numpy==1.16.1
  - pandas
  - nltk
  - scikit-learn
  - matplotlib
  - networkx
  - nltk
  - pip
  - pip:
    - umap-learn
    - swifter
    - gensim
    - spacy_lefff